CREATE TABLE movies (
    id           SERIAL PRIMARY KEY,
    title        VARCHAR(512)                                                                NOT NULL,
    release_date DATE,
    runtime      INTEGER,
    mpaa_rating  VARCHAR(10),
    description  TEXT,
    image        VARCHAR(255),
    video        VARCHAR(255),
    created_at   TIMESTAMP                                         DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP                                         DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_rating  DECIMAL(2, 1) CHECK (user_rating BETWEEN 0 AND 5) DEFAULT NULL
);

CREATE TRIGGER set_timestamp_movies
    BEFORE UPDATE
    ON movies
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Insert sample data
INSERT INTO movies (title, release_date, runtime, mpaa_rating, description, image, video, user_rating, created_at, updated_at)
VALUES ('Highlander', '1986-03-07', 116, 'R',
        'He fought his first battle on the Scottish Highlands in 1536. He will fight his greatest battle on the streets of New York City in 1986. His name is Connor MacLeod. He is immortal.',
        '8Z8dptJEypuLoOQro1WugD855YE', 'omOZyLmNMJs', 4.4, NOW(), NOW()),
       ('Raiders of the Lost Ark', '1981-06-12', 115, 'PG-13',
        'Archaeology professor Indiana Jones ventures to seize a biblical artefact known as the Ark of the Covenant. While doing so, he puts up a fight against Renee and a troop of Nazis.',
        '/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', '0xQSIdSRlAk', 4.8,NOW(), NOW()),
       ('The Godfather', '1972-03-24', 175, '18A',
        'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.',
        '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'UaVTIH8mujA', 4.9, NOW(), NOW()),
       ('The Shawshank Redemption', '1994-09-23', 142, 'R',
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'q6y0Go1tsGEsmtFryDOJo3dEmqu',
        'PLl99DlL6b4', 4.9, NOW(), NOW()),
       ('The Dark Knight', '2008-07-18', 152, 'PG-13',
        'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
        'qJ2tW6WMUDux911r6m7haRef0WH',
        'EXeTwQWrcwY', 4.8, NOW(), NOW()),
       ('Inception', '2010-07-16', 148, 'PG-13',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        'edv5CZvWj09upOsy2Y6IwDhK8bt',
        'YoHD9XEInc0', 4.7, NOW(), NOW()),
       ('Fight Club', '1999-10-15', 139, 'R',
        'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
        'bptfVGEQuv6vDTIMVCHjJ9Dz8PX',
        'qtRKdVHc-cE', 3.9, NOW(), NOW()),
       ('Pulp Fiction', '1994-10-14', 154, 'R',
        'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        'd5iIlFn5s0ImszYzBPb8JPIfbXD',
        's7EdQ4FqbhY', 4.6, NOW(), NOW()),
       ('Forrest Gump', '1994-07-06', 142, 'PG-13',
        'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
        'saHP97rTPS5eLmrLQEcANmKrsFl',
        'bLvqoHBptjg', 4.7, NOW(), NOW()),
       ('The Matrix', '1999-03-31', 136, 'R',
        'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        'f89U3ADr1oiB1s9GkdPOEpXUk5H',
        'vKQi3bBA1y8', 4.8, NOW(), NOW()),
       ('The Lord of the Rings: The Fellowship of the Ring', '2001-12-19', 178, 'PG-13',
        'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.',
        '6oom5QYQ2yQTMJIbnvbkBL9cHo6',
        'V75dMMIW2B4', 4.9, NOW(), NOW()),
       ('The Lord of the Rings: The Two Towers', '2002-12-18', 179, 'PG-13',
        'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman.',
        'rrGlNlzFTrXFNGXsD7NNlxq4BPb',
        'hYcw5ksV8YQ', 4.9, NOW(), NOW()),
       ('The Lord of the Rings: The Return of the King', '2003-12-17', 201, 'PG-13',
        'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
        'rCzpDGLbOoPwLjy3OAm5NUPOTrC',
        'r5X-hFf6Bwo', 4.9, NOW(), NOW()),
       ('Interstellar', '2014-11-07', 169, 'PG-13',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
        'gEU2QniE6E77NI6lCU6MxlNBvIx',
        'zSWdZVtXT7E', 4.7, NOW(), NOW()),
       ('Gladiator', '2000-05-05', 155, 'R',
        'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        'ty8TGRuvJLPUmAR1H1nRIsgwvim',
        'owK1qxDselE', 4.3, NOW(), NOW()),
       ('The Lion King', '1994-06-24', 88, 'G',
        'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
        'sKCr78MXSLixwmZ8DyJLrpMsd15',
        '4sj1MT05lAA', 4.8, NOW(), NOW()),
       ('Saving Private Ryan', '1998-07-24', 169, 'R',
        'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
        'uqx37cS8cpHg8U35f9U5IBlrCV3',
        '9CiW_DgxCnQ', 4.9, NOW(), NOW()),
       ('Schindler''s List', '1993-12-15', 195, 'R',
        'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
        'c8Ass7acuOe4za6DhSattE359gr',
        'gG22XNhtnoY', 4.9, NOW(), NOW()),
       ('The Silence of the Lambs', '1991-02-14', 118, 'R',
        'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
        'rplLJ2hPcOQmkFhTqUte0MkEaO2',
        'W6Mm8Sbe__o', 4.8, NOW(), NOW()),
       ('Se7en', '1995-09-22', 127, 'R',
        'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
        '69Sns8WoET6CfaYlIkHbla4l7nC',
        'znmZoVkCjpI', 4.7, NOW(), NOW());
