name: Deploy to AWS ECS

env:
    ECR_REPO: 100381574725.dkr.ecr.us-east-1.amazonaws.com/movie-search/server

on:
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to AWS ECR
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  mask-password: true

            - name: Build and Push Docker Image
              run: |
                  docker build -t $ECR_REPO:latest ./server
                  docker push $ECR_REPO:latest

            - name: Deploy ECS Task Definition with Secrets
              run: |
                  aws ecs update-service --cluster movie-search-cluster --service movie-search-server --force-new-deployment
