name: Terraform Apply

on:
    workflow_dispatch:  # Run manually

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Initialize Terraform
              run: |
                  cd infrastructure
                  terraform init

            - name: Apply Terraform
              run: |
                  cd infrastructure
                  terraform apply -auto-approve
